######################################################################
# Automatically generated by qmake (3.0) Fri Oct 15 16:25:19 2021
######################################################################

TEMPLATE = app
TARGET = source
INCLUDEPATH += .
LIBS += -pthread
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
QT += gui widgets
# Input
SOURCES += hw2.cpp
HEADERS += hw2.h
